### ISSUE TITLE
Прошлые версии EmbedVkGallery 

### ISSUE THREAD

**Issue by dokxpi** [bahek2462774/jquery.EmbedVkGallery#10]
Добрый вечер!

Очень печально,
Вот недавно перестало работать, не подскажите почему? (конструкция старая)
https://gist.github.com/dokxpi/09031da54e9715979bb99d1c77bc3f2e
https://www.tokarprofi.com/p/foto-galyareya.html

**Comment by bahek2462774** [comment]
@dokxpi Вк поставил лимит по дефолту = 50.
Егоможно указать вручную (какой максимум я не помню, но у меня на демо сайте стоит 1000)
Вот комит который это фиксит https://github.com/bahek2462774/jquery.EmbedVkGallery/commit/39a3269d3314237db40728d341533d2254368988

**Comment by dokxpi** [comment]
Жаль что нельзя на сервер нельзя заливать файлы, vkgallery.php и прочее, чтобы идти за вашими обновлениями 

А можно как то это ограничение обойти, в старой версии?  
Я правильно понимаю, что нужно править вот эти две строчки 
https://gist.github.com/dokxpi/09031da54e9715979bb99d1c77bc3f2e#file-index-vkimage-html-L100
https://gist.github.com/dokxpi/09031da54e9715979bb99d1c77bc3f2e#file-index-vkimage-html-L101
И на выходе должно получится так
Вместо 
```
   $loader_blinding_block.fadeOut(500).fadeIn(500);
                }, 1000);
```
Должно быть 
```
   $loader_blinding_block.fadeOut(500).fadeIn(500);
                }, 50);

```
Так?

**Comment by bahek2462774** [comment]
@dokxpi За моими обновлениями можно идти. Если вы у себя будете держать все файлы кроме vkgallery.php  - скрипт все равно будет работать. Так как он обращается к моему php файлу на моем хостинге. 

Просто обновите свой файл и все должно работать

**Comment by dokxpi** [comment]
Спасибо Вам большое,
С наступающим и успехов!

**Comment by dokxpi** [comment]
> Спасибо Вам большое,
> С наступающим и успехов!



> @dokxpi За моими обновлениями можно идти. Если вы у себя будете держать все файлы кроме vkgallery.php - скрипт все равно будет работать. Так как он обращается к моему php файлу на моем хостинге.
> 
> Просто обновите свой файл и все должно работать

Добрый день.
Подскажите, снова что-то изменилось?
