### ISSUE TITLE
Перестал работать скрипт после обновления API ВК

### ISSUE THREAD

**Issue by yalesnikov** [bahek2462774/jquery.EmbedVkGallery#12]
Здравствуйте. 

В консоле ошибка:

`error_msg: "Invalid request: versions below 5.81 are deprecated. Version param should be passed as \"v\". \"version\" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates"
`

На сайте ошибка:

`Album not found`

Не могли бы Вы обновить скрипт?

**Comment by bahek2462774** [comment]
Добрый день. Спасибо. Попробую сегодня пофиксить

**Comment by yalesnikov** [comment]
Добрый день. Вижу репозиторий обновился несколько дней назад, подскажите была ли исправлена найденная мною ошибка?

**Comment by bahek2462774** [comment]
добрый день. да.
Там обновился api у вк. и некоторые параметры поменялись (например
вмусто src стало url)
