### ISSUE TITLE
Плагин листает превью фотографий альбома, вместо их просмотра

### ISSUE THREAD

**Issue by dokxpi** [bahek2462774/jquery.EmbedVkGallery#2]
![1](https://cloud.githubusercontent.com/assets/10334512/22812263/5a0767a4-ef4c-11e6-8143-2c70676a53f7.png)
Я случайно обнаружил, то что после кадрирования листинг реанимируется
![2](https://cloud.githubusercontent.com/assets/10334512/22812297/8cef5122-ef4c-11e6-8383-ce65dd6a0931.png)
Результат 
![3](https://cloud.githubusercontent.com/assets/10334512/22812392/1a8fea00-ef4d-11e6-86bd-265980c479f3.png)
Результат спустя суток (What?)
![1](https://cloud.githubusercontent.com/assets/10334512/22812263/5a0767a4-ef4c-11e6-8143-2c70676a53f7.png)

Страница альбома ВК: https://goo.gl/azPiRf
Страница где работает jquery.EmbedVkGallery: https://goo.gl/fR8Uh3
Как я подключал jquery.EmbedVkGallery: https://gist.github.com/dokxpi/49ab256d3703c62dd5c274c52c2dc8ff

Что можете сказать по этому поводу?  В чем может быть проблема?

**Comment by bahek2462774** [comment]
Добавил параметр full_image_size
README:
full_image_size = Размер картинки, которая будет открыватся по клику (по умолчанию = 'x')
Если скрипт не находит нужную картинку - попытается взять сначала 'm', потом 's'.
Если ничего не найдено - пропустит эту картинку.
Все описания форматов есть в доке к VK API https://vk.com/dev/photo_sizes

**Comment by dokxpi** [comment]
Большое вам человеческое Спасибо! За быстрое реагирование! За ответы! И за помощь!
