### ISSUE TITLE
Медленный интернет требует индикатор загрузки альбома 

### ISSUE THREAD

**Issue by dokxpi** [bahek2462774/jquery.EmbedVkGallery#3]
Суть в том, что когда я поделился ссылкой на альбом (https://goo.gl/MKezv8), мне сообщили что,  там нечего нет, а конкретно альбома. 
Проблема таково, что большинство не будет ждать так долго и как правило такова страница будет закрывается... Итог - альбом некто не удивил

**Comment by bahek2462774** [comment]
добавил сообщение. Так же сделал - чтоб троеточие мигало. Хотя бы как то видно - что что-то происходит на сайте )).
