### ISSUE TITLE
Загрузка 2+ альбомов из Вконтакте на одной странице

### ISSUE THREAD

**Issue by dokxpi** [bahek2462774/jquery.EmbedVkGallery#4]
Может, кому-то пригодится
![321](https://cloud.githubusercontent.com/assets/10334512/23333513/655fc57e-fb95-11e6-8ada-58a7a676a188.png)
[Пример](https://jsfiddle.net/dokxpi/se9jovcf/2/)

**Comment by dokxpi** [comment]
Единственная проблема, во всех вкладках, кроме первой, фотографии выглядят не очень  и я не бес понятия как попроще перетянуть эти параметры во  второю, третью (и так далее) вкладку
   ```
(function($) {
 $(function() {
        var nps = 'EmbedVkGallery';
        $[nps] = {
            /**
             * Can be [s,m,x,o,p,q,y,z,w]
             * Look into https://vk.com/dev/photo_sizes
             */
            full_image_size: 'x',
            width: 100,
            margin: 4,
            rev: 1,
            link: '',
            link_mapper: function(el){
                return [
                    el.href,
                    '<a href="'+el.href+'">'+el.title+'</a>'
                ]
            }
        }; 
``` 


**Хорошо**
![321](https://cloud.githubusercontent.com/assets/10334512/23333764/24bf64fc-fb9a-11e6-8c4b-421018ce2283.png)


**Плохо**

![4321](https://cloud.githubusercontent.com/assets/10334512/23333768/31f00bf4-fb9a-11e6-92f9-240cc1117924.png)


Надеюсь автор подскажет как можно  решить эту проблему

**Comment by bahek2462774** [comment]
Загрузить 2+ альбомов на одной странице - возможно. Скрипт не как не припятствует этому.
Но вы же пытаетесь загрузить во вкладке (в скрытый DIV у которого display: none).

В таком случае - я не могу определить нормально ширину. И соответсвенно последующие картинки тоже с неправильной шириной.

В вашем случае - я бы запускал инициализацию скрипта только когда уже вкладка отобразилась . Это даст возможность скрипту нормально просчитать ширину дива и картинок.
Вот немного переделал ваш пример. 
https://jsfiddle.net/se9jovcf/4/

**Comment by dokxpi** [comment]
@bahek2462774 идеально!
На будущее, чтобы не возвращаться к этой тему, попытался загрузить три альбома 

https://jsfiddle.net/dokxpi/se9jovcf/6/
Подскажите, что я делаю не так?

**Comment by bahek2462774** [comment]
https://jsfiddle.net/se9jovcf/7/

**Comment by strannikone** [comment]
Добрый день!
А есть какой то способ увеличить скорость загрузки? ну или что-бы скрипт обрабатывал не сразу весь альбом (т.к. он очень большой, а делить его не хотелось бы)

**Comment by bahek2462774** [comment]
@strannikone Скорость зависит от скорости интернета юзера (ну и от скорости отдачи картинок серверами вк). Повлиять я тут никак не могу к сожалению.

Добавил параметр limit. Можно использовать как атрибут data-limit="5" или добавлять в объект когда передаете в плагин
$('.vk').EmbedVkGallery({limit: 5});
Лимит будет просто загружать картинки по лимиту (остальные картинки загружаться не будут)
