### ISSUE TITLE
Большой альбом

### ISSUE THREAD

**Issue by strannikone** [bahek2462774/jquery.EmbedVkGallery#5]
Добрый день!
А есть какой то способ увеличить скорость загрузки? ну или что-бы скрипт обрабатывал не сразу весь альбом (т.к. он очень большой, а делить его не хотелось бы)

**Comment by bahek2462774** [comment]
ДОбавил параметр limit. Будут загружены и показаны только определенное кол-во картинок.
Если limit = 0 или не указан или больше чем общее кол-во картинок - то будет показаны все картинки в альбоме.
