### ISSUE TITLE
Одинаковые по размеру фото и рандомные из альбома

### ISSUE THREAD

**Issue by iabarinov** [bahek2462774/jquery.EmbedVkGallery#6]
Привет. Очень крутой плагин, огромное спасибо тебе. А как сделать чтобы фото всегда были одного размера, а не меняли размер на следующей строчке?

Возможно ли сделать вывод случайных фото при загрузке страницы и чтобы они были разные при каждом обновлении?

**Comment by bahek2462774** [comment]
Добавил параметр shuffle для перемешивания массива с картинками.

Чтоб все фото были одного размера - надо много чего переписывать. К сожалению времени на это нет. Плагин вообще делался джастфофан. Сейчас бы я написать по другому все ).
Если есть желание и возможность - можете сделать пул реквест - с радостью приму.
