### ISSUE TITLE
EmbedVkGallery больше не работает

### ISSUE THREAD

**Issue by dokxpi** [bahek2462774/jquery.EmbedVkGallery#9]
Отсюда вопрос, 
планируется ли в дальнейшем добавление обновления (исправления ошибок) ?

Заранее благодарен за ответ

**Comment by bahek2462774** [comment]
Вроде все работает. И на демо сайте ?
Провреьте , актуальная ли версия у вас плагина

**Comment by dokxpi** [comment]
Видимо, время когда обнаружилась проблема, совпало с время профилактических работ на серверах  Вконтакте.  На данный момент всё работает, включая демо-версию. Извините за ложный сигнал
Зы. оставил [старую версию плагина ](https://gist.github.com/dokxpi/49ab256d3703c62dd5c274c52c2dc8ff)
